import { ToastContainer } from "react-toastify";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Providers from "./features/Providers";
import "react-toastify/dist/ReactToastify.css";
import "./styles/main.scss";

import { Manrope } from "next/font/google";

const manrope = Manrope({
	subsets: ["greek"],
	weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
	title: "Audiophile",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={manrope.className}>
				<Providers>
					<ToastContainer
						position="top-right"
						autoClose={1000}
						hideProgressBar={false}
						newestOnTop={false}
						closeOnClick
						rtl={false}
						pauseOnFocusLoss
						draggable
						pauseOnHover={false}
						theme="dark"
					/>
					<Header />
					<main>{children}</main>
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
